#!/usr/bin/env bash

function __rerole {
  command rerole $@ 1>&3

  # exit if __reroleRoleName file does not exist
  # indicates that a command was run or selection
  # was cancelled
  [ ! -f __reroleRoleName ] && exit

  local role=$(cat __reroleRoleName)
  rm __reroleRoleName

  echo 'eval $(assume-role' $role')'
}

function rerole {
  exec 3>&1
  eval "$(__rerole $@)"
}
